name: wheels

on:
  workflow_dispatch:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_PyPI:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make README links absolute
        run: |
          cd tools
          ./make_readme_links_absolute.sh > README-PyPI.md
          rm README.md
          mv README-PyPI.md README.md

      - name: Build
        run: pipx run build

      - name: Check
        run: pipx run twine check dist/*

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # PyPI does not allow replacing a file. Without this flag the entire action fails if even a single duplicate exists.
          skip-existing: true
          verbose: true
          # Real PyPI:
#          password: ${{ secrets.PYPI_API_TOKEN }}
          # Test PyPI:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/